// Dictionnaire des expressions et sigles médico-sociaux, utilisé par le
// bouton "Dictionnaire" de l'éditeur (RDPote.html).
// Pour ajouter/retirer une expression, il suffit de modifier ce tableau :
// aucune autre modification n'est nécessaire, la recherche et l'affichage
// s'adaptent automatiquement à son contenu.
const DICTIONNAIRE_EXPRESSIONS = [
"la ministre de la santé, des familles, de l'autonomie et des personnes handicapées, Stéphanie Rist,",
"la ministre déléguée chargée de l'autonomie et des personnes handicapées, Charlotte Parmentier-Lecocq,",
"le ministre de l'enseignement supérieur, de la recherche et de l'espace, Philippe Baptiste,",
"la ministre de l'action et des comptes publics, Amélie de Montchalin",
  "l'American Society of Clinical Oncology (ASCO)",
  "l'allocation personnalisée d'autonomie (APA)",
  "l'Assistance publique-hôpitaux de Paris (AP-HP)",
  "l'Autorité de sûreté nucléaire et de radioprotection (ASNR)",
  "l'Agence nationale de recherche sur le sida et les hépatites virales - maladies infectieuses émergentes (ANRS-MIE)",
  "l'allocation aux adultes handicapés (AAH)",
  "l'Agence centrale des organismes de sécurité sociale (Acoss)",
  "l'aide à l'acquisition d'une complémentaire santé (ACS)",
  "l'Agence de la transition écologique (Ademe)",
  "association départementale de parents et amis de personnes handicapées mentales (Adapei)",
  "l'Association des établissements du service public de santé mentale (Adesm)",
  "l'Association pour le droit de mourir dans la dignité (ADMD)",
  "l'Union nationale de l'aide à domicile en milieu rural (ADMR)",
  "l'Association des directeurs au service des personnes âgées (AD-PA)",
  "l'Association des enseignants et des écoles d'infirmiers de bloc opératoire (Aeeibo)",
  "l'Association française des directeurs des soins (AFDS)",
  "l'Agence fédérale d'information mutualiste (Afim)",
  "l'Association des journalistes de l'information sociale (Ajis)",
  "autorisation de mise sur le marché (AMM)",
  "l'Association des médecins urgentistes de France (Amuf)",
  "l'assistance médicale à la procréation (AMP, PMA)",
  "l'Agence nationale de la performance sanitaire et médico-sociale (Anap)",
  "l'Association nationale des centres hospitaliers locaux (ANCHL)",
  "l'Association nationale des directeurs d'écoles paramédicales (Andep)",
  "l'Association nationale des étudiants en médecine de France (Anemf)",
  "l'Agence nationale d'évaluation et de la qualité des établissements et services sociaux et médico-sociaux (Anesm)",
  "l'Association pour le développement des ressources humaines dans les établissements sanitaires et sociaux (Adrhess)",
  "l'Agence nationale pour l'amélioration des conditions de travail (Anact)",
  "Agence nationale de la sécurité des systèmes d'information (Anssi)",
  "l'Association nationale pour la formation permanente du personnel hospitalier (ANFH)",
  "l'Association nationale de prévention en alcoologie et addictologie (Anpaa)",
  "l'Agence nationale de sécurité sanitaire, de l'alimentation, de l'environnement et du travail (Anses)",
  "l'Association nationale des puéricultrices diplômées et des étudiants (ANPDE)",
  "l'Agence nationale de sécurité du médicament et des produits de santé (ANSM)",
  "l'Association pour la promotion de l'assurance collective (APAC)",
  "l'Association des paralysés de France (APF)",
  "l'Assistance publique-hôpitaux de Marseille (AP-HM)",
  "l'agence régionale de santé (ARS)",
  "un agent des services hospitaliers (ASH)",
  "l'Agence des systèmes d'information partagés de santé (Asip santé)",
  "l'allocation de solidarité pour les personnes âgées (Aspa)",
  "l'Agence technique de l'information sur l'hospitalisation (ATIH)",
  "accidents du travail et maladies professionnelles (AT-MP)",
  "l'Association de gestion du fonds pour l'insertion des personnes handicapées (Agefiph)",
  "l'Association nationale des directeurs et coordonnateurs de Clic (ANC.Clic)",
  "l'Association nationale française des infirmières et infirmiers diplômés et étudiants (Anfiide)",
  "l'Autorité de contrôle prudentiel et de résolution (ACPR)",
  "amélioration du service médical rendu (ASMR)",
  "l'Alliance pour les sciences de la vie et la santé (Aviesan)",
  "l'allocation journalière d'accompagnement d'une personne en fin de vie",
  "l'Association départementale de parents et amis de personnes handicapées mentales (Adapei)",
  "l'Agence de services et de paiement (ASP)",
    "la branche associative sanitaire, sociale et médico-sociale privée à but non lucratif (BASSMS)",
  "la bronchopneumopathie chronique obstructive (BPCO)",
  "l'union syndicale Le Bloc, qui regroupe l'UCDF, le Syndicat des gynécologues-obstétriciens de France (Syngof) et le Syndicat des anesthésistes libéraux (AAL)",
  "la commission d'évaluation économique et de santé publique (Ceesp) de la Haute autorité de santé (HAS)",
  "la commission de la transparence (CT) de la Haute autorité de santé (HAS)",
  "la Commission d'accès aux documents administratifs (Cada)",
  "la Centrale d'achats de l'hospitalisation privée et publique (Cahpp)",
  "la Centrale d'achat de l'informatique hospitalière (CAIH)",
  "le Centre d'accueil et de soins hospitaliers (Cash) de Nanterre",
  "le comité de veille et d'anticipation des risques sanitaires (Covars)",
  "le Conseil économique, social et environnemental (Cese)",
  "la Caisse nationale de l'assurance maladie (Cnam)",
  "la Caisse autonome de retraite des médecins de France (Carmf)",
  "les commissions de conciliation et d'indemnisation (CCI) régionales",
  "la Caisse nationale d'assurance vieillesse (Cnav)",
  "la Caisse nationale de solidarité pour l'autonomie (CNSA)",
  "la conférence régionale de la santé et de l'autonomie (CRSA)",
  "la Caisse d'assurance retraite et de la santé au travail (Carsat)",
  "le centre hospitalier universitaire (CHU)",
  "la Caisse nationale de retraites des agents des collectivités locales (CNRACL)",
  "le Collectif interassociatif sur la santé (Ciss)",
  "le comité national d'investissement en santé (Cnis)",
  "la couverture maladie universelle complémentaire (CMU-C)",
  "contrat d'engagement de service public (CESP)",
  "la Caisse d'amortissement de la dette sociale (Cades)",
  "le Syndicat des cadres hospitaliers Force ouvrière (CH-FO)",
  "communauté hospitalière de territoire (CHT)",
  "la Commission indépendante sur l'inceste et les violences sexuelles faites aux enfants (Ciivise)",
  "le Centre national des professions de santé (CNPS)",
  "le Comité national de l'organisation sanitaire et sociale (Cnoss)",
  "les centres locaux d'information et de coordination (Clic)",
  "le Comité économique des produits de santé (CEPS)",
  "Le Comité d'entente des formations infirmières et cadres (Cefiec)",
  "centre mémoire de ressources et de recherche (CMRR)",
  "le Comité consultatif national d'éthique pour les sciences de la vie et de la santé (CCNE)",
  "le Conseil national consultatif des personnes handicapées (CNCPH)",
  "le Conseil national de l'ordre des médecins (Cnom)",
  "le Conseil national de l'ordre des masseurs-kinésithérapeutes (CNOMK)",
  "le Conseil national de l'ordre des pédicures-podologues (Cnopp)",
  "la Confédération nationale des syndicats dentaires (CNSD)",
  "un contrat pluriannuel d'objectifs et de moyens (CPOM)",
  "un comité d'hygiène, de sécurité et des conditions de travail (CHSCT)",
  "le Centre technique des institutions de prévoyance (CTIP)",
  "une caisse primaire d'assurance maladie (CPAM)",
  "la Confédération des syndicats médicaux français (CSMF)",
  "la Conférence nationale des présidents de commission médicale d'établissement (CME) des centres hospitaliers (CH)",
  "la Conférence nationale des présidents de commission médicale d'établissement (CME) de centres hospitaliers spécialisés (CHS)",
  "le Centre régional des oeuvres universitaires et scolaires (Crous)",
  "le Comité d'entente des formations infirmières et cadres (Cefiec)",
  "crédit d'impôt compétitivité emploi (Cice)",
  "un centre médico-psycho-pédagogique (CMPP)",
  "convention d'objectifs et de gestion (COG)",
  "le Comité national pour la bientraitance et les droits (CNBD)",
  "Comité d'entente des écoles préparant aux métiers de l'enfance (CEEPAME)",
  "La commission/conférence médicale d'établissement (CME)",
  "les centres communaux d'action sociale (CCAS)",
  "le Centre national de l'expertise hospitalière (CNEH)",
  "comité d'hygiène, de sécurité et des conditions de travail (CHSCT)",
  "les centres d'action médico-sociale précoce (Camsp)",
  "les centres médico-psycho-pédagogiques (CMPP)",
  "Collectif interassociatif sur la santé (Ciss)",
  "la Commission nationale de l'informatique et des libertés (Cnil)",
  "Coordination nationale infirmière (CNI)",
  "la Conférence nationale des directeurs d'établissements pour personnes âgées et personnes handicapées (CNDEPAH)",
  "La contribution additionnelle de solidarité pour l'autonomie (Casa)",
  "le comité interministériel de la performance et de la modernisation de l'offre de soins hospitaliers (Copermo)",
  "communauté professionnelle territoriale de santé (CPTS)",
  "la commission régionale de conciliation et d'indemnisation (CRCI)",
  "le comité de réforme de la tarification hospitalière (Coretah)",
  "la classification commune des actes médicaux (CCAM)",
  "centre de soins, d'accompagnement et de prévention en addictologie (Csapa)",
  "centre d'accueil et d'accompagnement à la réduction des risques pour usagers de drogues (Caarud)",
  "le Centre national de gestion des praticiens hospitaliers et des personnels de direction de la fonction publique hospitalière (CNG)",
  "la commission nationale d'évaluation des dispositifs médicaux et des technologies de santé (Cnedimts)",
  "les centres de ressources autisme (CRA)",
  "commission des soins infirmiers et rééducation médico-techniques (CSIRMT)",
  "commissions des droits et de l'autonomie des personnes handicapées (CDAPH)",
  "le Centre national de gestion (CNG)",
  "le Collège de la médecine générale (CMG)",
  "la Commission des accords de retraite et de prévoyance (Comarep)",
  "le Comité d'entente des écoles d'infirmiers anesthésistes (Ceeiade)",
  "le Comité d'entente des écoles préparant aux métiers de l'enfance (Ceepame)",
  "Comité de l'aide médicale urgente de la permanence des soins et des transports sanitaires (Codamups)",
  "comité de coordination régionale de la santé sexuelle (Coress)",
  "comité de coordination de la lutte contre l'infection par le virus de l'immunodéficience humaine (Corevih)",
  "Centre opérationnel de réception et de régulation des urgences sanitaires et sociales (Corruss)",
  "le Contrôleur général des lieux de privation de liberté (CGLPL)",
  "le crédit d'impôt compétitivité emploi (CICE)",
  "dotation annuelle de financement (DAF)",
  "déchets d'activité de soins à risques infectieux (Dasri)",
  "la direction générale de l'offre de soins (DGOS)",
  "la direction générale de la cohésion sociale (DGCS)",
  "la direction générale de la santé (DGS)",
  "la direction de la recherche, des études, de l'évaluation et des statistiques (Drees)",
  "déchets d'activité de soins à risque infectieux (Dasri)",
  "une direction régionale des entreprises, de la concurrence, de la consommation, du travail et de l'emploi (Direccte)",
  "le développement professionnel continu (DPC)",
  "la direction de la sécurité sociale (DSS)",
  "les directeurs d'établissements sanitaires, sociaux et médico-sociaux (D3S)",
  "le dossier médical partagé (DMP)",
  "dotation minimale de convergence (Dominic)",
  "direction régionale de la jeunesse, des sports et de la cohésion sociale (DRJSCS)",
  "délégation à la stratégie des systèmes d'information de santé (DSSIS)",
  "la direction générale de la concurrence, de la consommation et de la répression des fraudes (DGCCRF)",
  "dossier patient informatisé (DPI)",
  "la direction générale de la recherche, de l'innovation et du numérique en santé (DGRINES)",
  "établissement d'hébergement pour personnes âgées dépendantes (Ehpad)",
  "l'Ecole des hautes études en santé publique (EHESP)",
  "l'Ecole nationale de santé publique (ENSP, aujourd'hui EHESP)",
  "L'Ebitdar (excédent brut d'exploitation des secteurs opérationnels avant charges locatives ; ou juste \"excédent brut d'exploitation\")",
  "L'Ebitda (qui correspond à l'Ebitdar diminué des charges locatives)",
  "l'Ecole nationale supérieure de sécurité sociale (EN3S)",
  "état des prévisions de recettes et de dépenses (EPRD)",
  "état réalisé des recettes et des dépenses (ERRD)",
  "établissement de santé privé d'intérêt collectif (Espic)",
  "établissements et services d'aide par le travail (Esat)",
  "établissements et services médico-sociaux (ESMS)",
  "l'Autorité européenne de sécurité alimentaire (European Food Safety Authority -EFSA)",
  "espaces de réflexion éthique régionaux et interrégionaux (Ereri)",
  "la Fédération européenne des associations et industries pharmaceutiques (EFPIA)",
  "la Fédération hospitalière de France (FHF)",
  "la Fédération des établissements hospitaliers et d'aide à la personne privés solidaires (Fehap)",
  "La Fédération nationale indépendante des mutuelles (Fnim)",
  "la Fédération de l'hospitalisation privée (FHP)",
  "la Fédération nationale de la Mutualité française (FNMF)",
  "la Fédération française des associations de médecins coordonnateurs en Ehpad (Ffamco-Ehpad)",
  "la Fédération nationale des associations de directeurs d'établissements et services pour personnes âgées (Fnadepa)",
  "la Fédération nationale avenir et qualité de vie des personnes âgées (Fnaqpa)",
  "la Fédération nationale des associations de personnes âgées et de leurs familles (Fnapaef)",
  "la Fédération nationale des associations gestionnaires au service des personnes handicapées et fragiles (Fegapei)",
  "Le Fonds de financement de la protection complémentaire de la couverture universelle du risque maladie (Fonds CMU-C)",
  "l'association des accidentés de la vie (Fnath)",
  "la Fédération nationale des étudiant·e·s en sciences infirmières (Fnesi)",
  "la Fédération nationale des étudiants en kinésithérapie (Fnek)",
  "un foyer d'accueil médicalisé (FAM) / des foyers d'accueil médicalisés",
  "la Fédération nationale des infirmiers (FNI)",
  "la Fédération nationale indépendante des mutuelles (Fnim)",
  "la Fédération nationale des établissements d'hospitalisation à domicile (Fnehad)",
  "la Fédération française des masseurs-kinésithérapeutes rééducateurs (FFMKR)",
  "la Fédération des médecins de France (FMF)",
  "la Fédération des mutuelles de France (FMF)",
  "La Fédération nationale des associations gestionnaires au service des personnes handicapées et fragiles (Fegapei)",
  "la Fondation nationale de gérontologie (FNG)",
  "la Fédération nationale des centres de santé (FNCS)",
  "la Fédération nationale des associations d'usagers en psychiatrie (Fnapsy)",
  "La Fédération des syndicats pharmaceutiques de France (FSPF)",
  "foyers d'accueil médicalisé (FAM)",
  "la Fédération française des sociétés d'assurance (FFSA)",
  "le Fonds d'innovation organisationnelle en psychiatrie (Fiop)",
  "le Fonds national de prévention, d'éducation et d'informations sanitaires (FNPEIS)",
  "La Fédération nationale des orthophonistes (FNO)",
  "la Fédération française des associations de médecins coordinateurs en Ehpad (Ffamco-Ehpad)",
  "Fédération des spécialités médicales (FSM)",
  "la Fédération nationale des associations de l'aide familiale populaire (Fnaafp-CSF)",
  "fonds pour la modernisation des établissements de santé publics et privés (FMESPP)",
  "La Fédération nationale des opticiens de France (Fnof)",
  "la Fédération française des maisons et pôles de santé (FFMPS)",
  "la Fédération nationale des transporteurs sanitaires (FNTS)",
  "la Fédération nationale des artisans ambulanciers (Fnaa)",
  "la Fédération nationale des ambulanciers privés (Fnap)",
  "Fonds pour l'insertion des personnes handicapées dans la fonction publique (FIPHFP)",
  "Fédération des associations générales étudiantes (Fage)",
  "un groupement de coopération sociale et médico-sociale (GCSMS)",
  "un groupement territorial social et médico-social (GTSMS)",
  "groupement régional d'appui au développement de l'e-Santé (Grades)",
  "le Groupe national des établissements et services publics sociaux et médico-sociaux (Gepso)",
  "le Grade à accès fonctionnel (Graf)",
  "le groupe iso-ressources moyen pondéré (GMP)",
  "groupes homogènes de séjours (GHS)",
  "le Groupement des entreprises mutuelles d'assurance (Gema)",
  "groupements interrégionaux de recherche clinique et d'innovation (Girci)",
  "groupement de coopération sociale et médico-sociale (GCSMS)",
  "les groupes hospitalo-universitaires (GHU) de l'AP-HP",
  "le Haut conseil pour l'avenir de l'assurance maladie (HCAAM)",
  "la loi \"Hôpital, patients, santé et territoires\" (HPST) de 2009",
  "la Haute autorité de santé (HAS)",
  "l'hospitalisation à domicile (HAD)",
  "Haut conseil des professions paramédicales (HCPP)",
  "le Haut conseil de la santé publique (HCSP)",
  "les infirmiers de bloc opératoire diplômés d'Etat (Ibode)",
  "l'Inspection générale des affaires sociales (Igas)",
  "incitation financière à la qualité (Ifaq)",
  "l'Institut de recherche et documentation en économie de la santé (Irdes)",
  "l'Institut national de la santé et de la recherche médicale (Inserm)",
  "l'Institut national des études démographiques (Ined)",
  "l'Institut national de la statistique et des études économiques (Insee)",
  "l'Institut national de recherche pour l'agriculture, l'alimentation et l'environnement (Inrae)",
  "l'Institut national de prévention et d'éducation pour la santé (Inpes)",
  "institut de formation en soins infirmiers (Ifsi)",
  "les instituts de formation des masseurs-kinésithérapeutes (IFMK)",
  "L'Intersyndicale nationale des internes (Isni)",
  "l'Intersyndicat national des chefs de clinique et assistants (ISNCCA)",
  "l'Institut national du cancer (Inca)",
  "l'Intersyndicat des praticiens d'exercice hospitalier et hospitalo-universitaire (INPH)",
  "l'Institut national de recherche et de sécurité pour la prévention des accidents du travail et des maladies professionnelles (INRS)",
  "l'Institut pour la recherche en santé publique (Iresp)",
  "l'Intersyndicale nationale autonome représentative des internes de médecine générale (Isnar-IMG)",
  "les instituts thérapeutiques, éducatifs et pédagogiques (Itep)",
  "l'Institut de veille sanitaire (InVS)",
  "instituts de formation des aides-soignants (Ifas)",
  "l'Institut national de recherche en sciences et technologies du numérique (Inria)",
  "les indicateurs de qualité et de sécurité des soins (IQSS)",
  "l'Institution de retraite complémentaire des agents non titulaires de l'Etat et des collectivités publiques (Ircantec)",
  "le Journal of the American Medical Association (JAMA).",
  "liste des produits et prestations (LPP) remboursables",
  "le Leem (Les entreprises du médicament)",
  "le LET (Les entreprises de télésanté)",
  "le Laboratoire français du fractionnement et des biotechnologies (LFB)",
  "maisons départementales des personnes handicapées (MDPH)",
  "les maisons pour l'autonomie et l'intégration des malades d'Alzheimer (Maia)",
  "méthode d'action pour l'intégration des services d'aide et de soins dans le champ de l'autonomie",
  "la Mutuelle nationale des hospitaliers (MNH)",
  "la Mutualité sociale agricole (MSA)",
  "médecine, chirurgie, obstétrique (MCO)",
  "maisons d'accueil spécialisées (MAS)",
  "la Mutuelle générale de l'éducation nationale (MGEN)",
  "les missions d'intérêt général et d'aide à la contractualisation (Migac)",
  "la mission interministérielle de vigilance et de lutte contre les dérives sectaires (Miviludes)",
  "mission d'évaluation et de contrôle des lois de financement de la sécurité sociale (Mecss)",
  "les Merri (missions d'enseignement, de recherche, de référence et d'innovation)",
  "les maîtres de conférences des universités-praticiens hospitaliers (MCU-PH)",
  "l'Association nationale des médecins coordonnateurs en Ehpad et du secteur médico-social (Mcoor)",
  "la nomenclature générale des actes professionnels (NGAP)",
  "stéatohépatite non alcoolique (NASH)",
  "la Nouvelle union écologiste populaire et sociale (Nupes)",
  "objectif national des dépenses d'assurance maladie (Ondam)",
  "L'ordre national des infirmiers (ONI)",
  "l'organisme gestionnaire du développement professionnel continu (OGDPC)",
  "l'objectif général de dépenses (OGD)",
  "l'Observatoire national de la fin de vie (ONFV)",
  "l'Organisation nationale des syndicats de sages-femmes (ONSSF)",
  "l'Office national d'indemnisation des accidents médicaux (Oniam)",
  "l'Observatoire de la décentralisation et de l'action sociale (Odas)",
  "L'Ordre national des chirurgiens-dentistes (ONCD)",
  "l'Organisme commun des institutions de rente et de prévoyance (Ocirp)",
  "l'Organisation nationale des syndicats d'infirmiers libéraux (Onsil)",
  "l'observatoire national des professions de santé (ONDPS)",
  "l'office parlementaire d'évaluation des choix scientifiques et technologiques (Opecst)",
  "odds ratio (OR, mesure approchant le risque relatif)",
  "option pratique tarifaire maîtrisée (Optam)",
  "pôles d'activités et de soins adaptés (Pasa)",
  "programme de médicalisation des systèmes d'information (PMSI)",
  "la première année commune aux études de santé (Paces)",
  "les composés alkylés per- et polyfluorés (PFAS), dits \"polluants éternels\"",
  "la prime de fonctions et de résultats (PFR)",
  "la prestation de compensation du handicap (PCH)",
  "Provence-Alpes-Côte d'Azur (Paca)",
  "praticiens territoriaux de médecine générale (PTMG)",
  "parcours de santé des personnes âgées en risque de perte d'autonomie (Paerpa)",
  "le Pathos moyen pondéré (PMP)",
  "les permanences d'accès aux soins de santé (Pass)",
  "le programme d'accompagnement des handicaps et de la perte d'autonomie (Priac)",
  "les professeurs des universités-praticiens hospitaliers (PU-PH)",
  "programmes d'accompagnement du retour à domicile (Prado)",
  "la permanence des soins ambulatoires (PDSA)",
  "le projet de loi d'approbation des comptes de la sécurité sociale (Placss)",
  "la qualité de vie et des conditions de travail (QVCT)",
  "la secrétaire d'Etat à la famille, aux personnes âgées et à l'autonomie, Laurence Rossignol",
  "le Régime social des indépendants (RSI)",
  "ratio différentiel coût-résultat (RDCR)",
  "le répertoire partagé des professionnels de santé (RPPS)",
  "la rémunération sur objectifs de santé publique (Rosp)",
  "le regroupement autonome des généralistes jeunes installés et remplaçants (Réagjir)",
  "du syndicat de jeunes médecins généralistes installés et remplaçants Reagjir",
  "le Regroupement national des organisations gestionnaires de centres de santé (RNOGCS)",
  "la récupération améliorée après chirurgie (Raac)",
  "le Réseau des acheteurs hospitaliers (Resah)",
  "le référentiel des actes innovants hors nomenclature (RIHN)",
  "le virus Sars-CoV-2",
  "le Syndicat des biologistes (SDBIO)",
  "Syndicat des laboratoires de biologie clinique (SLBC)",
  "le Syndicat national des médecins des hôpitaux publics (Snam-HP)",
  "le Syndicat national des établissements et résidences privés pour personnes âgées (Synerpa)",
  "services de soins infirmiers à domicile (Ssiad)",
  "le Syndicat des médecins libéraux (SML)",
  "soins médicaux et de réadaptation (SMR)",
  "soins de suite et de réadaptation (SSR, devenus SSR)",
  "le Syndicat des employeurs associatifs de l'action sociale et médico-sociale (Syneas)",
  "la Société française de gériatrie et gérontologie (SFGG)",
  "service d'accompagnement médico-social pour les adultes handicapés (Samsah)",
  "le Syndicat national des instituts de formation en masso-kinésithérapie (Snifmk)",
  "le Syndicat national des infirmières et infirmiers libéraux (Sniil)",
  "les services d'aide et d'accompagnement à domicile (Saad)",
  "les services départementaux d'incendie et de secours (Sdis)",
  "la Société française d'accompagnement et de soins palliatifs (Sfap)",
  "le secrétariat général des ministères sociaux",
  "le Syndicat des manageurs publics de santé (SMPS)",
  "le Syndicat national autonome des orthoptistes (SNAO)",
  "le Syndicat national des médecins biologistes (SNMB)",
  "le Syndicat national des jeunes médecins généralistes (SNJMG)",
  "Le Syndicat national des masseurs-kinésithérapeutes rééducateurs (SNMKR)",
  "le Syndicat national des professionnels infirmiers (SNPI-CFE-CGC)",
  "le Syndicat des orthoptistes de France (SOF)",
  "le schéma régional d'organisation des soins (Sros)",
  "le Syndicat national français des ergothérapeutes libéraux (Synfel)",
  "le Syndicat des instituts de formation en ergothérapie français (Sifef)",
  "les services d'éducation et de soins à domicile (Sessad)",
  "les services autonomie aide et soins (Saas)",
  "les services polyvalents d'aide et de soins à domicile (Spasad)",
  "le Système national d'information inter-régimes de l'assurance maladie (Sniiram)",
  "le service de santé des armées (SSA)",
  "le Syndicat des employeurs associatifs action sociale et santé (Syneas)",
  "le Syndicat national des inspecteurs de l'action sanitaire et sociale (Sniass-Unsa)",
  "Syndicat national des infirmiers anesthésistes (Snia)",
  "les services d'accompagnement à la vie sociale (SAVS)",
  "le Syndicat national des ophtalmologistes de France (Snof)",
  "le Syndicat national des infirmières et infirmiers éducateurs de santé (Snies-Unsa)",
  "La société d'assurance mutuelle du secteur sanitaire, social et médico-social Sham",
  "Société française de médecine d'urgence (SFMU)",
  "le Syndicat national des directeurs, cadres, médecins, chirurgiens-dentistes et pharmaciens des établissements sanitaires et sociaux publics et privés-CFDT (Syncass-CFDT)",
  "le Syndicat national des enseignants de médecine générale (SNEMG)",
  "le Syndicat national des infirmières conseillères de santé (Snics-FSU)",
  "service mobile d'urgence et de réanimation (Smur)",
  "le Syndicat national de l'industrie des technologies médicales (Snitem)",
  "le secrétariat général pour l'investissement (SGPI)",
  "le système national des données de santé (SNDS)",
  "le service médical rendu (SMR)",
  "tests rapides d'orientation diagnostique (Trod)",
  "trouble de déficit de l'attention avec ou sans hyperactivité (TDAH)",
  "les troubles du neurodéveloppement (TND)",
  "l'Union nationale et syndicale des sages-femmes (UNSSF)",
  "unités cognitivo-comportementales (UCC)",
  "l'Union nationale de l'aide, des soins et des services aux domiciles (UNA)",
  "l'Union nationale des associations familiales (Unaf)",
  "l'Union nationale des caisses d'assurance maladie (Uncam)",
  "unité hospitalière spécialement aménagée (UHSA)",
  "l'Union des fédérations et syndicats nationaux d'employeurs sans but lucratif du secteur sanitaire, médico-social et social (Unifed)",
  "l'Union nationale interfédérale des oeuvres et organismes privés sanitaires et sociaux (Uniopss)",
  "l'Union nationale des internes, chefs de clinique et assistants en radiologie (Unir)",
  "l'Union nationale des organismes complémentaires d'assurance maladie (Unocam)",
  "l'Union des groupements d'achats publics (Ugap)",
  "union pour la gestion des établissements des caisses d'assurance maladie (Ugecam)",
  "unités d'hébergement renforcées (UHR)",
  "unité de soins de longue durée (USLD)",
  "l'Union nationale des professions libérales (UNAPL)",
  "l'Union nationale des associations d'infirmiers de bloc opératoire diplômés d'Etat (Unaibode)",
  "L'Union nationale des associations de parents, de personnes handicapées mentales et de leurs amis (Unapei)",
  "l'union régionale des professionnels de santé (URPS)",
  "l'Union nationale des amis et familles de malades psychiques (Unafam)",
  "l'Union des syndicats de pharmaciens d'officine (Uspo)",
  "unité pour malades difficiles (UMD)",
  "l'Union nationale des omnipraticiens français (Unof-CSMF)",
  "Union nationale des centres communaux d'action sociale (Unccas)",
  "l'Union nationale des professionnels de santé (UNPS)",
  "l'Union des caisses nationales de sécurité sociale (Ucanss)",
  "l'Union nationale des médecins spécialistes confédérés (Umespe)",
  "l'Union nationale des réseaux de santé (UNRS)",
  "l'Union française pour une médecine libre (UFML)",
  "l'union de recouvrement des cotisations sociales et des allocations familiales (Urssaf)",
  "le syndicat Union française pour une médecine libre (UFML-S)",
  "le virus respiratoire syncytial (VRS)"
];
